# set your authorization key
@auth_key = keyboard_cat

#### Fetch users

POST http://localhost:3000/api/users/get?authorization_key={{auth_key}} HTTP/1.1
Content-Type: application/json

{
  "role": "ADMIN",
  "skip": 0,
  "take": 15,
  "keyword": "j"
}

#### Fetch user

POST http://localhost:3000/api/user/get?authorization_key={{auth_key}} HTTP/1.1
Content-Type: application/json

{
  "id": "1aa5b375-a1a9-40f3-9ff2-c887e7b3c463"
}

#### Disable/ Enable user's account

POST http://localhost:3000/api/user/toggle?authorization_key={{auth_key}} HTTP/1.1
Content-Type: application/json

{
  "id": "1aa5b375-a1a9-40f3-9ff2-c887e7b3c463",
  "state": false
}

#### Set user's role

POST http://localhost:3000/api/user/set-role?authorization_key={{auth_key}} HTTP/1.1
Content-Type: application/json

{
  "email": "jagaitera@paterostechnologicalcollege.edu.ph",
  "role": "ADMIN"
}

#### Remove user's role (also disables the account)

POST http://localhost:3000/api/user/remove-role?authorization_key={{auth_key}} HTTP/1.1
Content-Type: application/json

{
  "email": "jagaitera@paterostechnologicalcollege.edu.ph"
}

#### Fetch departments

POST http://localhost:3000/api/departments/get?authorization_key={{auth_key}} HTTP/1.1

#### Create department

POST http://localhost:3000/api/department/create?authorization_key={{auth_key}} HTTP/1.1
Content-Type: application/json

{
  "name": "Bachelor of Science in Information Technology",
  "alias": "BSIT",
  "color": "#FFFFFF"
}

#### Update department

POST http://localhost:3000/api/department/update?authorization_key={{auth_key}} HTTP/1.1
Content-Type: application/json

{
  "id": "6ff82103-1fc7-49ae-b956-2f9f81482e6b",
  "name": "Bachelor of Science in Information Technology",
  "alias": "BSIT",
  "color": "#6A1B9A"
}

#### Disable/ Enable department

POST http://localhost:3000/api/department/toggle?authorization_key={{auth_key}} HTTP/1.1
Content-Type: application/json

{
  "id": "6ff82103-1fc7-49ae-b956-2f9f81482e6b",
  "state": false
}

#### Delete department

POST http://localhost:3000/api/department/delete?authorization_key={{auth_key}} HTTP/1.1
Content-Type: application/json

{
  "id": "2fc8ecd6-58a0-445d-aea9-f8d154eaa60e"
}
